#!/bin/bash
unzip mock2.tar
dnf install httpd -y
systemctl enable --now httpd
firewall-cmd  --permanent --add-service=http
firewall-cmd --reload
cp webcontents2/*  /var/www/html/
systemctl restart httpd
wget localhost/s
sh s

rm -rvf mock2
echo "Script is Ended"
echo "ALL the Very BEST!!!!"
echo "Dont forget reboot the machine after done configuration in consoles"